name: flutter_study
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobile_scanner: ^3.4.1
  webview_flutter: ^4.2.2
  pull_to_refresh: ^2.0.0
  dio: ^5.3.2
  json_annotation: ^4.8.1
  shared_preferences: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.1
  pedantic_mono: any

flutter:
  uses-material-design: true
