name: flutter_study
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_toggle_tab: ^1.3.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  scroll_date_picker: ^3.7.1
  shared_preferences: ^2.1.1
  flutter_riverpod: ^2.3.6
  uuid: ^3.0.7
  riverpod_annotation: ^2.1.1
  riverpod_generator: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.5
  custom_lint: ^0.4.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  pedantic_mono: any
  riverpod_lint: ^1.3.2
flutter:
  uses-material-design: true
