name: flutter_study
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  mobile_scanner: ^3.2.0
  webview_flutter: ^4.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any
flutter:
  uses-material-design: true
